version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: .
          name: Run Build
          command: |
            dotnet build
  publish:
      docker:
        - image: mcr.microsoft.com/dotnet/sdk:6.0
      steps:
        - checkout
        - run:
            working_directory: .
            name: Run Build
            command: |
              apt update && apt install zip -y
              dotnet publish -c Release -p:PublishReadyToRun=false
              zip -r hashiversion.zip . -i bin/Debug/Release/net6.0
        - store_artifacts:
            path: hashiversion.zip
            destination: hashiversion.zip

workflows:
  Deployment: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build
      - publish